name: Docker Image CI

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: dockerimage_group_${{ github.ref }}
  cancel-in-progress: true

jobs:
  # The docker image
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout Step
      - uses: actions/checkout@v3

      # Github Container Registry
      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Setup Step
      - name: Set env
        id: tag_env
        env:
          SHA_TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          LATEST_TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        run: |
          export SHA_7=$(echo $GITHUB_SHA | head -c7)
          echo "SHA_TAG=$SHA_TAG:$SHA_7" >> $GITHUB_ENV
          echo "STAGING_TAG=$STAGING_TAG" >> $GITHUB_ENV
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      # Build Step
      - name: Build container image
        run: docker build --file ./Dockerfile -t ${{ env.SHA_TAG }} .

      # Push Container Image Step
      - name: Push image to GitHub Container Registry
        run: docker push ${{ env.SHA_TAG }}

      # Tag as latest if on main
      - name: Retag Docker Image latest
        if: github.ref == 'refs/heads/main'
        run: docker tag ${{ env.SHA_TAG }} ${{ env.LATEST_TAG }} && docker push ${{ env.LATEST_TAG }}
